import { profile } from '../content/profile.js';
import { site } from '../content/site.js';
export const e = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export const arrow = '<span aria-hidden="true">↗</span>';
export const external = (url,label,cls='') => `<a class="${cls}" href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(label)} ${arrow}</a>`;
export const tags = items => `<ul class="tags" aria-label="Skills">${items.map(x=>`<li>${e(x)}</li>`).join('')}</ul>`;
export function header(active='') {
 return `<a class="skip" href="#main">Skip to content</a><header class="header"><div class="wrap header-inner"><a class="identity" href="/" aria-label="Keith Janish, home"><span class="monogram">KJ<span>.</span></span><span>KEITH JANISH<small>GAMEPLAY PROGRAMMER</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu <span aria-hidden="true">+</span></button><nav id="navigation" aria-label="Main navigation">${site.navigation.map(n=>`<a href="${n.href}" ${active===n.label?'aria-current="page"':''}>${n.label}</a>`).join('')}<a class="resume-link" href="${profile.resume}" target="_blank" rel="noopener">Résumé ${arrow}</a></nav></div></header>`;
}
export function footer(){return `<footer><div class="wrap footer-inner"><a href="/" class="footer-name">KEITH JANISH<span>.</span></a><span>Gameplay, with intention.</span><a href="#top">Back to top ↑</a><small>© ${new Date().getFullYear()} Keith Janish</small></div></footer>`;}
export function contact(){return `<section id="contact" class="contact section"><div class="wrap contact-grid"><div><p class="eyebrow">LET’S CONNECT</p><h2>${site.contactTitle.split('\n').map(e).join('<br>')}</h2><p>${e(site.contactDescription)}</p></div><div class="contact-actions"><a class="email-link" href="mailto:${profile.email}">${e(profile.email)} ${arrow}</a><div class="contact-secondary">${external(profile.linkedin,'LinkedIn')}<button id="copy-email" data-email="${profile.email}">Copy email <span aria-hidden="true">⧉</span></button><a href="${profile.resume}" download>Download résumé ↓</a></div><p class="copy-status" aria-live="polite"></p><span class="availability">${e(profile.availability)}</span></div></div></section>`;}
export function page({title=site.title,description=site.description,body}){return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#141416"><title>${e(title)}</title><meta name="description" content="${e(description)}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:type" content="website"><link rel="icon" href="/favicon-keith-v109.ico?v=mauve" sizes="any"><link rel="icon" href="/favicon-keith-v109.svg?v=mauve" type="image/svg+xml"><link rel="apple-touch-icon" href="/apple-touch-icon-keith-v109.png?v=mauve"><link rel="stylesheet" href="/assets/style.css"><script type="module" src="/assets/project-filters.js"></script><script type="module" src="/assets/project-carousel.js"></script><script type="module" src="/assets/main.js"></script></head><body id="top">${body}</body></html>`;}
